### ISSUE TITLE
Can't skip the data loss frame in the IsochronousStream class 

### ISSUE THREAD

**Issue by Jade-source** [Peter-St/Android-UVC-Camera#10]
Hi, Peter-St

I found that in the Galaxy(android 9 series) accepts packets with data loss without skipping them.

As far as I've checked, IsochronousStream Class can't skip the problematic frame.
The reason seems to be the lack of defensive code to detect frames.

In IsochronousStream class, the current header length, flag, and data length are only detected,
So frame detection is improved by adding FID and EOF, but skip is not perfect.

![26 03 2020_18 05 17](https://user-images.githubusercontent.com/55683133/78314297-824e4a80-7594-11ea-855a-47298a8b1542.jpg)

**Comment by Peter-St** [comment]
You are right.

I experimented some time ago on this behavior, but wasn't able to solve it.
Any help would be welcome to solve this issue.

**Comment by Peter-St** [comment]
The latest Approach over the LibUsb Driver should solve this issue. Update the app to the latest version and set up the Camera with the LibUsb driver.
