### ISSUE TITLE
Unable to see preview screen in android 10 device

### ISSUE THREAD

**Issue by habi-kvana** [Peter-St/Android-UVC-Camera#14]
if i change target version to below 28 then it will work in android 9 and 10 devices. but in here it is not showing camera 
 preview.

**Comment by Peter-St** [comment]
Hello,

this is due to a bug from Google, which they are not solving.
It is explained here:

https://github.com/saki4510t/UVCPermissionTest/issues/1

Peter

**Comment by Peter-St** [comment]
All Android Versions are supported by now. Most of the bugs have been fixed by Google. (Some Devs still not work....)
