### ISSUE TITLE
Rendering on USB camera content using OpenGL

### ISSUE THREAD

**Issue by habi-kvana** [Peter-St/Android-UVC-Camera#16]
StartIsoStreamActivity----> processReceivedMJpegVideoFrameKamera() -->  glsurface --- > render other image on frame

can we render those images frame data on glsurface?

**Comment by Peter-St** [comment]
Hello,

the surface view I think accepts PixelFormat.RGB_888.

processReceivedMJpegVideoFrameKamera() returns a jpeg which is useless I think for rendering to a glsufaceview.

You would have to convert the mjpeg to RGBX Pixel Format.
