### ISSUE TITLE
Preview not displaying for external camera

### ISSUE THREAD

**Issue by habi-kvana** [Peter-St/Android-UVC-Camera#19]
Preview is not displaying for external camera product-id: 102, vendor-id" 4057
<img width="803" alt="Screenshot 2021-03-23 at 5 40 28 PM" src="https://user-images.githubusercontent.com/15380858/112146259-60b0fd80-8c01-11eb-8262-c34d28c0bc28.png">

**Comment by Peter-St** [comment]
Hello,

you have to find out, if the camera is an uvc device:
On a Linux System run this command:

lsusb -v -d xxxx:xxxx
The first 4 x are the product and the second 4 x are the vendor id.
If you can run this command successfully, you can attach the output.

Thanks, Peter

**Comment by habi-kvana** [comment]
thanks for responding @Peter-St 
I resolved this issue after opening the camera we should get SupportedSize and then pass one of those resolutions then it will display preview.
