### ISSUE TITLE
Pure Termal Issue

### ISSUE THREAD

**Issue by Peter-St** [Peter-St/Android-UVC-Camera#20]
> @ 38293312可以将纯热固件升级到版本1.3.0，然后重试吗？
> https://github.com/groupgets/purethermal1-firmware/releases
Yes, I upgraded the firmware of PT2, but the phone still can’t use it normally
Please watch the test video： https://www.youtube.com/watch?v=3SFKlTRe-G0
![image](https://user-images.githubusercontent.com/21971730/112951397-e25adb00-916d-11eb-9b41-9473acc142bd.png)

_Originally posted by @38293312 in https://github.com/Peter-St/Android-UVC-Camera/issues/18#issuecomment-809992625_

**Comment by Peter-St** [comment]
> > @ 38293312嗯，这似乎不是应用程序问题。它甚至没有检测到纯热板。我建议尝试使用其他电缆以确保其USB OTG。一旦您连接pt2板，Android甚至应该在启动该应用之前对其进行检测。
> 
> It can be checked that PT2 is UVC. Just click the default option to open it with the APP, just like disconnecting the UVC from the mobile phone. For the same mobile phone, I can use another OTG thermal imaging camera normally with OTG

**Comment by Peter-St** [comment]
> This is the parameter of "PT2 + LEPTON3.5" viewed from the PC software "Lepton User App"
> 
> ![image](https://user-images.githubusercontent.com/21971730/112917468-47dea580-9135-11eb-90e0-16c11b184cde.png)
> ![image](https://user-images.githubusercontent.com/21971730/112917563-7a889e00-9135-11eb-9548-039c6caadc4f.png)
> 
> ![image](https://user-images.githubusercontent.com/21971730/112917483-4e6d1d00-9135-11eb-9cfc-b1f7b2999fe0.png)
> ![image](https://user-images.githubusercontent.com/21971730/112917500-57f68500-9135-11eb-8ccc-68989a6bca2b.png)
> 
> ![image](https://user-images.githubusercontent.com/21971730/112917534-68a6fb00-9135-11eb-9b29-6c053793e489.png)
> ![image](https://user-images.githubusercontent.com/21971730/112917539-6cd31880-9135-11eb-98c2-e8db408d9e2a.png)

**Comment by Peter-St** [comment]
> I use PT2+LEPTON3.5, APP "UYVY_support.apk" test. Failed!
> 
> ![Screenshot_20210330_084607_humer uvc_camera](https://user-images.githubusercontent.com/21971730/112917264-e1f21e00-9134-11eb-9991-6a43b4eee86a.jpg)
> ![Screenshot_20210330_084625_humer uvc_camera](https://user-images.githubusercontent.com/21971730/112917270-e4547800-9134-11eb-87e8-a6e87c754b57.jpg)
> ![Screenshot_20210330_084627_humer uvc_camera](https://user-images.githubusercontent.com/21971730/112917275-e61e3b80-9134-11eb-903d-1d34a6415ea4.jpg)
> ![Screenshot_20210330_084642_humer uvc_camera](https://user-images.githubusercontent.com/21971730/112917280-e7e7ff00-9134-11eb-8ebc-0b9f55fc516f.jpg)
> ![Screenshot_20210330_084651_humer uvc_camera](https://user-images.githubusercontent.com/21971730/112917284-e9b1c280-9134-11eb-972b-695ed866e3a4.jpg)
> 
> After the above problem occurs, unplug the OTG and reconnect it, the following content is displayed
> ![Screenshot_20210330_090040_humer uvc_camera](https://user-images.githubusercontent.com/21971730/112918021-8759c180-9136-11eb-9092-2cec67a00dfb.jpg)

**Comment by Peter-St** [comment]
> @38293312 May you upgrade the purethermal firmware to version 1.3.0 and try again?
> https://github.com/groupgets/purethermal1-firmware/releases

**Comment by 38293312** [comment]
I upgraded the PT2 to the 1.3 firmware, and it failed. Here is the test video: https://www.youtube.com/watch?v=3SFKlTRe-G0&t=15s

**Comment by Peter-St** [comment]
Closed
