### ISSUE TITLE
Execution failed for task ':app:ndkBuild'. > Process 'command 'E:\android-ndk-r22b/ndk-build.cmd'' finished with non-zero exit value 2

### ISSUE THREAD

**Issue by kashawnwaris321** [Peter-St/Android-UVC-Camera#21]

**Comment by Peter-St** [comment]
Hello kashawnwaris321,

looks like there is something not right configured in your Android Studio. Set the SDK and NDK path right in you local.properties file and try to use google to find an answer for this error.

So far,

Peter

**Comment by Peter-St** [comment]
Build System has changed from Autotools to Cmake.

You can give em another try.
