### ISSUE TITLE
Getting error when importing the  project

### ISSUE THREAD

**Issue by EworkitSrl** [Peter-St/Android-UVC-Camera#22]
the error is  fatal error: '/home/peter/Android/Sdk/ndk/21.1.6352462/sysroot/usr/include/android/native_window.h' file not found

**Comment by Peter-St** [comment]
Hello EworkitSrl,

looks like you have not configured your Android Studio ndk plugins right. 
In the local.properties file set your SDK and NDK location. I would suggest to google for an solution for this error message.

So far,

Peter

**Comment by Peter-St** [comment]
Build System has changed from Autotools to Cmake.

You can give em another try
