### ISSUE TITLE
预览会卡顿问题

### ISSUE THREAD

**Issue by manxialiunian** [Peter-St/Android-UVC-Camera#24]
您好，我们在拉取代码编译安装到手机上，外接usb相机，预览都是OK的；但是usb相机对着密密麻麻的方格布块时，会出现卡顿的现象，麻烦看看是什么问题。

https://user-images.githubusercontent.com/15249057/141757308-3f423c35-d98f-448f-b562-204372466221.mp4

**Comment by Peter-St** [comment]
Hi,

I figured out, that this issue was due to bad memory allocation. With the latest update (thanks to UVC Camera App from Saki) this issue could be solved.

So far,

Peter

**Comment by manxialiunian** [comment]
收到！
