### ISSUE TITLE
WebRTC crashing 

### ISSUE THREAD

**Issue by lchandp** [Peter-St/Android-UVC-Camera#26]
Compiled the source and uvc camera working on Android 9. 

But testing the webrtc, the device is crashing and throwing the following message

11-24 07:11:37.689  6366  6618 D From Native: UVC_STREAM_ERR --> Package 12
11-24 07:11:37.689  6366  6618 D From Native: UVC_STREAM_ERR --> Package 13
11-24 07:11:37.689  6366  6618 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3 in tid 6618 (IntentService[W), pid 6366 (umer.uvc_camera)
11-24 07:11:37.811  6629  6629 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
11-24 07:11:37.812  3272  3272 I /system/bin/tombstoned: received crash request for pid 6618
11-24 07:11:37.812  6629  6629 I crash_dump32: performing dump of process 6366 (target tid = 6618)
11-24 07:11:37.849  6629  6629 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-24 07:11:37.849  6629  6629 F DEBUG   : Build fingerprint: 'Amlogic/franklin/franklin:9/PPR1.180610.011/20210913:userdebug/test-keys'
11-24 07:11:37.849  6629  6629 F DEBUG   : Revision: '0'
11-24 07:11:37.849  6629  6629 F DEBUG   : ABI: 'arm'
11-24 07:11:37.849  6629  6629 F DEBUG   : pid: 6366, tid: 6618, name: IntentService[W  >>> humer.uvc_camera <<<
11-24 07:11:37.849  6629  6629 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3
11-24 07:11:37.849  6629  6629 F DEBUG   : Cause: null pointer dereference
11-24 07:11:37.849  6629  6629 F DEBUG   :     r0  0000008d  r1  00000020  r2  9a9fa5f9  r3  00000003
11-24 07:11:37.849  6629  6629 F DEBUG   :     r4  93ab624c  r5  0000000e  r6  93ab6324  r7  0000000c
11-24 07:11:37.849  6629  6629 F DEBUG   :     r8  00000000  r9  926b1040  r10 8eb27400  r11 8ee8ade8
11-24 07:11:37.849  6629  6629 F DEBUG   :     ip  926b1014  sp  8ee8adc0  lr  926aabe0  pc  926aac30
11-24 07:11:38.075  6629  6629 F DEBUG   : 
11-24 07:11:38.075  6629  6629 F DEBUG   : backtrace:
11-24 07:11:38.075  6629  6629 F DEBUG   :     #00 pc 0000ec30  /data/app/humer.uvc_camera-LwypGrpriOEug48kSJD0PA==/lib/arm/libUvc_Support.so (cb_jni_WebRtc_Service+204)
11-24 07:11:38.075  6629  6629 F DEBUG   :     #01 pc 00006f11  /data/app/humer.uvc_camera-LwypGrpriOEug48kSJD0PA==/lib/arm/libusb1.0.so
11-24 07:11:38.075  6629  6629 F DEBUG   :     #02 pc 0000ad97  /data/app/humer.uvc_camera-LwypGrpriOEug48kSJD0PA==/lib/arm/libusb1.0.so
11-24 07:11:38.075  6629  6629 F DEBUG   :     #03 pc 00009b4f  /data/app/humer.uvc_camera-LwypGrpriOEug48kSJD0PA==/lib/arm/libusb1.0.so
11-24 07:11:38.075  6629  6629 F DEBUG   :     #04 pc 0000773b  /data/app/humer.uvc_camera-LwypGrpriOEug48kSJD0PA==/lib/arm/libusb1.0.so
11-24 07:11:38.075  6629  6629 F DEBUG   :     #05 pc 00007333  /data/app/humer.uvc_camera-LwypGrpriOEug48kSJD0PA==/lib/arm/libusb1.0.so (libusb_handle_events_timeout_completed+238)
11-24 07:11:38.075  6629  6629 F DEBUG   :     #06 pc 000077bf  /data/app/humer.uvc_camera-LwypGrpriOEug48kSJD0PA==/lib/arm/libusb1.0.so (libusb_handle_events+16)
11-24 07:11:38.075  6629  6629 F DEBUG   :     #07 pc 0000f264  /data/app/humer.uvc_camera-LwypGrpriOEug48kSJD0PA==/lib/arm/libUvc_Support.so (lunchTheStream_WebRtc_Service+524)
11-24 07:11:38.075  6629  6629 F DEBUG   :     #08 pc 00010ce0  /data/app/humer.uvc_camera-LwypGrpriOEug48kSJD0PA==/lib/arm/libjnidispatch.so (ffi_call_SYSV+44)
11-24 07:11:38.075  6629  6629 F DEBUG   :     #09 pc 00010840  /data/app/humer.uvc_camera-LwypGrpriOEug48kSJD0PA==/lib/arm/libjnidispatch.so (ffi_call+304)
11-24 07:11:38.075  6629  6629 F DEBUG   :     #10 pc 000057b0  /data/app/humer.uvc_camera-LwypGrpriOEug48kSJD0PA==/lib/arm/libjnidispatch.so
11-24 07:11:38.075  6629  6629 F DEBUG   :     #11 pc 000079b4  /data/app/humer.uvc_camera-LwypGrpriOEug48kSJD0PA==/lib/arm/libjnidispatch.so (Java_com_sun_jna_Native_invokeVoid+44)
11-24 07:11:38.075  6629  6629 F DEBUG   :     #12 pc 0041c279  /system/lib/libart.so (art_quick_generic_jni_trampoline+40)
11-24 07:11:38.075  6629  6629 F DEBUG   :     #13 pc 00417d75  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
11-24 07:11:38.075  6629  6629 F DEBUG   :     #14 pc 003f13eb  /system/lib/libart.so (art_quick_invoke_static_stub+222)
11-24 07:11:38.075  6629  6629 F DEBUG   :     #15 pc 000a1043  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+154)
11-24 07:11:38.075  6629  6629 F DEBUG   :     #16 pc 001e8835  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+232)
11-24 07:11:38.075  6629  6629 F DEBUG   :     #17 pc 001e3511  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+776)
11-24 07:11:38.075  6629  6629 F DEBUG   :     #18 pc 003eceeb  /system/lib/libart.so (MterpInvokeStatic+130)
11-24 07:11:38.076  6629  6629 F DEBUG   :     #19 pc 0040ab94  /system/lib/libart.so (ExecuteMterpImpl+14612)
11-24 07:11:38.076  6629  6629 F DEBUG   :     #20 pc 00267284  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/humer.uvc_camera-LwypGrpriOEug48kSJD0PA==/base.apk (deleted) (com.sun.jna.Function.invoke+960)
11-24 07:11:38.076  6629  6629 F DEBUG   :     #21 pc 001c7e89  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2193211614+352)
11-24 07:11:38.076  6629  6629 F DEBUG   :     #22 pc 001cc757  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-24 07:11:38.076  6629  6629 F DEBUG   :     #23 pc 001e34fb  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-24 07:11:38.076  6629  6629 F DEBUG   :     #24 pc 003ebf0f  /system/lib/libart.so (MterpInvokeVirtual+442)
11-24 07:11:38.076  6629  6629 F DEBUG   :     #25 pc 0040aa14  /system/lib/libart.so (ExecuteMterpImpl+14228)
11-24 07:11:38.076  6629  6629 F DEBUG   :     #26 pc 002673fc  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/humer.uvc_camera-LwypGrpriOEug48kSJD0PA==/base.apk (deleted) (com.sun.jna.Function.invoke+348)
11-24 07:11:38.076  6629  6629 F DEBUG   :     #27 pc 001c7e89  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2193211614+352)
11-24 07:11:38.076  6629  6629 F DEBUG   :     #28 pc 001cc757  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-24 07:11:38.076  6629  6629 F DEBUG   :     #29 pc 001e4377  /system/lib/libart.so (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+674)
11-24 07:11:38.076  6629  6629 F DEBUG   :     #30 pc 003ed149  /system/lib/libart.so (MterpInvokeVirtualRange+424)
11-24 07:11:38.076  6629  6629 F DEBUG   :     #31 pc 0040ad14  /system/lib/libart.so (ExecuteMterpImpl+14996)
11-24 07:11:38.076  6629  6629 F DEBUG   :     #32 pc 00268420  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/humer.uvc_camera-LwypGrpriOEug48kSJD0PA==/base.apk (deleted) (com.sun.jna.Library$Handler.invoke+520)
11-24 07:11:38.076  6629  6629 F DEBUG   :     #33 pc 001c7e89  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2193211614+352)
11-24 07:11:38.076  6629  6629 F DEBUG   :     #34 pc 001cc757  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-24 07:11:38.076  6629  6629 F DEBUG   :     #35 pc 001e34fb  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #36 pc 003ecadd  /system/lib/libart.so (MterpInvokeInterface+1020)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #37 pc 0040ac14  /system/lib/libart.so (ExecuteMterpImpl+14740)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #38 pc 000cd0be  /system/framework/boot.vdex (java.lang.reflect.Proxy.invoke+4)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #39 pc 001c7e89  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2193211614+352)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #40 pc 001cc6a3  /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+82)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #41 pc 003df753  /system/lib/libart.so (artQuickToInterpreterBridge+890)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #42 pc 0041c2ff  /system/lib/libart.so (art_quick_to_interpreter_bridge+30)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #43 pc 00417d75  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #44 pc 003f13eb  /system/lib/libart.so (art_quick_invoke_static_stub+222)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #45 pc 000a1043  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+154)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #46 pc 00350a6d  /system/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #47 pc 00351505  /system/lib/libart.so (art::InvokeWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+304)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #48 pc 0028b213  /system/lib/libart.so (art::JNI::CallStaticObjectMethodA(_JNIEnv*, _jclass*, _jmethodID*, jvalue*)+478)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #49 pc 000c852d  /system/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodA(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, jvalue*, art::Primitive::Type, art::InvokeType)+1172)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #50 pc 000b9055  /system/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallStaticObjectMethodA(_JNIEnv*, _jclass*, _jmethodID*, jvalue*)+40)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #51 pc 003c90b7  /system/lib/libart.so (art::InvokeProxyInvocationHandler(art::ScopedObjectAccessAlreadyRunnable&, char const*, _jobject*, _jobject*, std::__1::vector<jvalue, std::__1::allocator<jvalue>>&)+446)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #52 pc 003e0261  /system/lib/libart.so (artQuickProxyInvokeHandler+760)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #53 pc 0041c0d5  /system/lib/libart.so (art_quick_proxy_invoke_handler+20)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #54 pc 00417d75  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #55 pc 003f12e7  /system/lib/libart.so (art_quick_invoke_stub+226)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #56 pc 000a1031  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+136)
11-24 07:11:38.077  6629  6629 F DEBUG   :     #57 pc 001e8835  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+232)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #58 pc 001e3511  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+776)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #59 pc 003ecadd  /system/lib/libart.so (MterpInvokeInterface+1020)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #60 pc 0040ac14  /system/lib/libart.so (ExecuteMterpImpl+14740)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #61 pc 00261ac6  /dev/ashmem/dalvik-classes.dex extracted in memory from /data/app/humer.uvc_camera-LwypGrpriOEug48kSJD0PA==/base.apk (deleted) (com.example.androidthings.videortc.WebRtcService.onHandleIntent+82)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #62 pc 001c7e89  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2193211614+352)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #63 pc 001cc757  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #64 pc 001e34fb  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #65 pc 003ebf0f  /system/lib/libart.so (MterpInvokeVirtual+442)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #66 pc 0040aa14  /system/lib/libart.so (ExecuteMterpImpl+14228)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #67 pc 003a83f4  /system/framework/boot-framework.vdex (android.app.IntentService$ServiceHandler.handleMessage+12)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #68 pc 001c7e89  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2193211614+352)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #69 pc 001cc6a3  /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+82)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #70 pc 003df753  /system/lib/libart.so (artQuickToInterpreterBridge+890)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #71 pc 0041c2ff  /system/lib/libart.so (art_quick_to_interpreter_bridge+30)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #72 pc 0000f117  /dev/ashmem/dalvik-jit-code-cache (deleted) (android.os.Handler.dispatchMessage+126)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #73 pc 000230ad  /dev/ashmem/dalvik-jit-code-cache (deleted) (android.os.Looper.loop+1020)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #74 pc 00417d75  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #75 pc 003f13eb  /system/lib/libart.so (art_quick_invoke_static_stub+222)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #76 pc 000a1043  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+154)
11-24 07:11:38.078  6629  6629 F DEBUG   :     #77 pc 001e8835  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+232)
11-24 07:11:38.079  6629  6629 F DEBUG   :     #78 pc 001e3511  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+776)
11-24 07:11:38.079  6629  6629 F DEBUG   :     #79 pc 003eceeb  /system/lib/libart.so (MterpInvokeStatic+130)
11-24 07:11:38.079  6629  6629 F DEBUG   :     #80 pc 0040ab94  /system/lib/libart.so (ExecuteMterpImpl+14612)
11-24 07:11:38.079  6629  6629 F DEBUG   :     #81 pc 00ae3484  /system/framework/boot-framework.vdex (android.os.HandlerThread.run+56)
11-24 07:11:38.079  6629  6629 F DEBUG   :     #82 pc 001c7e89  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2193211614+352)
11-24 07:11:38.079  6629  6629 F DEBUG   :     #83 pc 001cc6a3  /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+82)
11-24 07:11:38.079  6629  6629 F DEBUG   :     #84 pc 003df753  /system/lib/libart.so (artQuickToInterpreterBridge+890)
11-24 07:11:38.079  6629  6629 F DEBUG   :     #85 pc 0041c2ff  /system/lib/libart.so (art_quick_to_interpreter_bridge+30)
11-24 07:11:38.079  6629  6629 F DEBUG   :     #86 pc 00417d75  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
11-24 07:11:38.079  6629  6629 F DEBUG   :     #87 pc 003f12e7  /system/lib/libart.so (art_quick_invoke_stub+226)
11-24 07:11:38.079  6629  6629 F DEBUG   :     #88 pc 000a1031  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+136)
11-24 07:11:38.079  6629  6629 F DEBUG   :     #89 pc 00350a6d  /system/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)
11-24 07:11:38.079  6629  6629 F DEBUG   :     #90 pc 003517f9  /system/lib/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+316)
11-24 07:11:38.079  6629  6629 F DEBUG   :     #91 pc 00373369  /system/lib/libart.so (art::Thread::CreateCallback(void*)+900)
11-24 07:11:38.079  6629  6629 F DEBUG   :     #92 pc 00063c15  /system/lib/libc.so (__pthread_start(void*)+22)
11-24 07:11:38.079  6629  6629 F DEBUG   :     #93 pc 0001e065  /system/lib/libc.so (__start_thread+22)
11-24 07:11:38.111  3180  5761 D audio_hw_subMixingFactory: out_standby_subMixingPCM: out_stream(0xa88de000) usecase: STREAM_PCM_NORMAL
11-24 07:11:38.111  3180  5761 I audio_hw_subMixingFactory: ++usecase_change_validate_l_sm(), dev usecase masks = 0x1, is_standby = 1, out usecase STREAM_PCM_NORMAL
11-24 07:11:38.111  3180  5761 I audio_hw_subMixingFactory: --usecase_change_validate_l_sm(), dev usecase masks = 0, is_standby = 1, out usecase STREAM_PCM_NORMAL
11-24 07:11:38.111  3180  5761 I amlaudioMixer: ++delete_mixer_input_port port ID: 0
11-24 07:11:38.111  3180  3400 E amlaudioMixer: mixer_do_mixing_16bit(), sys or direct pcm must exist!!!
11-24 07:11:38.450  6366  6625 D de.tavendo.autobahn.WebSocketReader: WebSocker reader running.
11-24 07:11:38.451  6366  6626 D de.tavendo.autobahn.WebSocketWriter: WebSocker writer running.
11-24 07:11:38.451  6366  6597 D de.tavendo.autobahn.WebSocketConnection: WebSocket writer created and started.
11-24 07:11:38.452  6366  6597 W WSChannelRTCClient: WebSocket register() in state NEW
11-24 07:11:38.461  6366  6597 D WSRTCClient: C->GAE: https://appr.tc/message/6164317/26579593. Message: {"sdp":"v=0\r\no=- 3622922814870200375 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE audio video\r\na=msid-semantic: WMS ARDAMS\r\nm=audio 9 UDP\/TLS\/RTP\/SAVPF 111 103 9 102 0 8 105 13 110 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:J\/m3\r\na=ice-pwd:tNSGDql9Db9zBgfqjHGfaYov\r\na=ice-options:trickle renomination\r\na=fingerprint:sha-256 BD:89:6D:8D:A0:06:16:53:7A:A9:3B:A4:7B:3A:79:D8:B3:95:1B:B4:98:68:57:5D:06:31:A9:9B:FB:10:DA:FE\r\na=setup:actpass\r\na=mid:audio\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:111 opus\/48000\/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC\/16000\r\na=rtpmap:9 G722\/8000\r\na=rtpmap:102 ILBC\/8000\r\na=rtpmap:0 PCMU\/8000\r\na=rtpmap:8 PCMA\/8000\r\na=rtpmap:105 CN\/16000\r\na=rtpmap:13 CN\/8000\r\na=rtpmap:110 telephone-event\/48000\r\na=rtpmap:113 telephone-event\/16000\r\na=rtpmap:126 telephone-event\/8000\r\na=ssrc:3996715550 cname:55TBSGefo\/7DpG0+\r\na=ssrc:3996715550 msid:ARDAMS ARDAMSa0\r\na=ssrc:3996715550 mslabel:ARDAMS\r\na=ssrc:3996715550 label:ARDAMSa0\r\nm=video 9 UDP\/TLS\/RTP\/SAVPF 96 97 98 99 100 101 127\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:J\/m3\r\na=ice-pwd:tNSGDql9Db9zBgfqjHGfaYov\r\na=ice-options:trickle renomination\r\na=fingerprint:sha-256 BD:89:6D:8D:A0:06:16:53:7A:A9:3B:A4:7B:3A:79:D8:B3:95:1B:B4:98:68:57:5D:06:31:A9:9B:FB:10:DA:FE\r\na=setup:actpass\r\na=mid:video\r\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:3 http:\/\/www.webrtc.org\/experiments\/rtp-hdrext\/abs-send-time\r\na=extmap:4 urn:3gpp:video-orientation\r\na=extmap:5 http:\/\/www.ietf.org\/id\/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:6 http:\/\/www.webrtc.org\/experiments\/rtp-hdrext\/playout-delay\r\na=extmap:7 http:\/\/www.webrtc.org\/experiments\/rtp-hdrext\/video-content-type\r\na=extmap:8 http:\/\/www.webrtc.org\/experiments\/rtp-hdrext\/video-timing\r\na=sendrecv\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8\/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx\/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP9\/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=rtpmap:99 rtx\/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 red\/90000\r\na=rtpmap:101 rtx\/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:127 ulpfec\/90000\r\na=ssrc-group:FID 2987521672 3652136281\r\na=ssrc:2987521672 cname:55TBSGefo\/7DpG0+\r\na=ssrc:2987521672 msid:ARDAMS ARDAMSv0\r\na=ssrc:2987521672 mslabel:ARDAMS\r\na=ssrc:2987521672 label:ARDAMSv0\r\na=ssrc:3652136281 cname:55TBSGefo\/7DpG0+\r\na=ssrc:3652136281 msid:ARDAMS ARDAMSv0\r\na=ssrc:3652136281 mslabel:ARDAMS\r\na=ssrc:3652136281 label:ARDAMSv0\r\n","type":"offer"}
11-24 07:11:38.463  6366  6597 D WSRTCClient: C->GAE: https://appr.tc/message/6164317/26579593. Message: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:640748585 1 udp 2122262783 2409:4071:2004:2fc0:2857:1514:c104:c127 43526 typ host generation 0 ufrag J\/m3 network-id 4 network-cost 10"}
11-24 07:11:38.465  6366  6597 D WSRTCClient: C->GAE: https://appr.tc/message/6164317/26579593. Message: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:540798933 1 udp 2122194687 192.168.43.77 47713 typ host generation 0 ufrag J\/m3 network-id 3 network-cost 10"}
11-24 07:11:38.477  6366  6597 D WSRTCClient: C->GAE: https://appr.tc/message/6164317/26579593. Message: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:842163049 1 udp 1685987071 157.45.95.4 47713 typ srflx raddr 192.168.43.77 rport 47713 generation 0 ufrag J\/m3 network-id 3 network-cost 10"}
11-24 07:11:38.545  3691  3834 W ServiceManagement: Waited one second for android.hardware.radio@1.0::IRadio/slot1. Waiting another...
11-24 07:11:38.618  3463  3546 E WifiVendorHal: getWifiLinkLayerStats(l.937) failed {.code = ERROR_NOT_AVAILABLE, .description = }
11-24 07:11:38.737  6366  6625 W de.tavendo.autobahn.WebSocketReader: Status: 101 (Switching Protocols)
11-24 07:11:38.741  6366  6597 D de.tavendo.autobahn.WebSocketConnection: opening handshake received
11-24 07:11:38.741  6366  6597 D WSChannelRTCClient: WebSocket connection opened to: wss://apprtc-ws.webrtc.org:443/ws
11-24 07:11:38.742  6366  6597 D WSChannelRTCClient: Registering WebSocket for room 6164317. ClientID: 26579593
11-24 07:11:38.742  6366  6597 D WSChannelRTCClient: C->WSS: {"cmd":"register","roomid":"6164317","clientid":"26579593"}
11-24 07:11:38.921  3463  3486 W WindowManager: Unable to start animation, surface is null or no children.
11-24 07:11:39.039  6366  6615 W libjingle: (paced_sender.cc:261): Elapsed time (2005 ms) longer than expected, limiting to 2000 ms
11-24 07:11:39.116  3180  3400 I amlaudioMixer: ++mixer_output_standby standby
11-24 07:11:39.116  3180  3400 I audio_hw_port: output_port_standby()
11-24 07:11:39.116  3180  3400 I amlaudioMixer: mixer_16b_threadloop() sleep
11-24 07:11:39.203  3206  3280 E BufferQueueProducer: [Toast#2] disconnect: not connected (req=1)
11-24 07:11:39.204  6366  6396 W libEGL  : EGLNativeWindowType 0x93b73008 disconnect failed
11-24 07:11:39.209  3463  3685 W NotificationService: Toast already killed. pkg=humer.uvc_camera callback=android.app.ITransientNotification$Stub$Proxy@c6b5304
11-24 07:11:39.214  3272  3272 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_12
11-24 07:11:39.217  3463  6644 W ActivityManager:   Force finishing activity humer.uvc_camera/com.example.androidthings.videortc.WebRtc_MainActivity
11-24 07:11:39.239  3463  6644 W ActivityManager:   Force finishing activity humer.uvc_camera/com.example.androidthings.videortc.CallActivity
11-24 07:11:39.251  3463  3478 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver

**Comment by Peter-St** [comment]
Hi,

I noticed the crash on WeRtc. There wil be major changes when using libusb with the camera and after this, I will rewrite the webrtc progress.

So far,

Peter

**Comment by Peter-St** [comment]
Hi Again,

I solved everything, but by the while AppRTC isn't running any more.

I decided to dismiss the WebRTC support
