### ISSUE TITLE
Video Probe-Commit Control failed!

### ISSUE THREAD

**Issue by zhimin-wang** [Peter-St/Android-UVC-Camera#28]
Hi ! 
I'm sorry for making these pictures below so big.
I downloaded the app from the google play.
I tried to set different parameters. One of these is shown as follows.
![07433f01e0cd57d16a1b9999733f9eb](https://user-images.githubusercontent.com/24918185/156597571-d5e4738f-926c-4ef0-a4ac-35974a247ffb.jpg)
However, when I click the "Video Probe-Commit Control" button, the message always shows below.
![c78a90e4d630e607e85463de462a14f](https://user-images.githubusercontent.com/24918185/156597858-209a4651-54f7-4f4d-a902-81eb6322cfe2.jpg)
I don't know why the 'Camera Frame Index' from the Camera Controltransfer is always equal to 0.
I will be appreciate it if you can help me.
Thank you very much for your contribution.
Some information is as follows.
![d99fb0201f0c1a82dce2fac763279e6](https://user-images.githubusercontent.com/24918185/156598982-9915cb1e-d3d5-41e0-9ce6-751d22b53b9c.jpg)

![157d0e99f7615df674e65f83bfad894](https://user-images.githubusercontent.com/24918185/156598589-c6fb14f1-936c-4245-b700-4dbd612798b7.jpg)

![6b7a4b2dc37c4e988ed333ad6fd04d4](https://user-images.githubusercontent.com/24918185/156598562-ba391859-3439-4f5b-baa7-210a3f3e4425.jpg)

**Comment by Peter-St** [comment]
Hello ZhiminWang96,

it seems to be, that there is a failure in my app.

I will update my app, than you can try it again, but it will take some time.

So far, Peter

**Comment by Peter-St** [comment]
Hi,

WebRTC is sadly discontinued, so I dropped the WebRTC support.

So far,

Peter
