### ISSUE TITLE
F-Droid availability

### ISSUE THREAD

**Issue by ZenitH-AT** [Peter-St/Android-UVC-Camera#35]
Will this app make its way to F-Droid?

**Comment by Peter-St** [comment]
HI,

a merge Request on the F-Droid Repo has been submitted. I think the app will in the next couple of days online in the F-Droid Store.

Thx, Peter

**Comment by essys** [comment]
It's online:
[https://f-droid.org/en/packages/humer.uvc_camera](https://f-droid.org/en/packages/humer.uvc_camera)

Many thanks for the app Peter.

**Comment by Korb** [comment]
> It's online: https://f-droid.org/en/packages/humer.uvc_camera

At [at IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/humer.uvc_camera?repo=main)
