### ISSUE TITLE
Camera Autofocus

### ISSUE THREAD

**Issue by costeacostin** [Peter-St/Android-UVC-Camera#4]
Hello,

Great job for this project, it was really useful for me after some magic params combinations. 
I use an UVC camera that is trying to autofocus. 
Do you think that it can be any chance to control the autofocus? at least to enable/disable it

Cheers,

**Comment by Peter-St** [comment]
Hello costeacostin,

thanks for using my app. I can handle the thing with the camera auto focus, but this will last some time. I'll get back to you, when it's done.

Peter

**Comment by costeacostin** [comment]
Thank you a lot. It will be really useful. If I will succeed to do this on my own I will also come back to you. Also I guess that we can use multiple cameras with these configurations (just a question)

**Comment by Peter-St** [comment]
Hello costeacostin,

I tried to add the autofocus for the camera, but I was not able to test the function. Please update the app from the repo, or reinstall it from Play Store and report, if the Auto Focus works.

So Far,

Peter

**Comment by Peter-St** [comment]
About multible cameras with these configuration, I will test it the next days ...
And if it works, I think I will update my App with this feature, but it will sure last some time.
Peter

**Comment by costeacostin** [comment]
I tried and it works, thank you a lot mate!

**Comment by Vanntreudy** [comment]
Hi! I am very new to android UVC Camera. I tried to set function getAutoFocus() auto when UVC Camera start, but I can't do. I don't where to start with. Should I config in Lib UVC Camera? Or where? Please Help me
